# Generated by Django 5.0.6 on 2024-06-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_student_email_remove_student_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField(default=18)),
                ('school_year', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.course')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.year')),
            ],
            options={
                'db_table': 'academics',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.section'),
        ),
    ]
